[package]
name = "xdp-mode-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
xdp-mode-common = { path = "../xdp-mode-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "xdp-mode"
path = "src/main.rs"
